server:
  JwtSecretKey: BoLhEpq3VraQQ+zLwcLk5ZVRSjqYLQ0SddWSJli6kgvyI293wZS2Iw==
mysql:
  MySQLHost: database
  MySQLPort: 3306
  MySQLUser: docker
  MySQLPassword: docker
  MySQLDatabaseName: docker
  MySQLConnectRetries: 10